const defaultStocks = [
  { symbol: "AAPL", name: "Apple", price: 185.7 },
  { symbol: "GOOGL", name: "Google", price: 425.3 },
  { symbol: "MSFT", name: "Microsoft", price: 312.8 },
  { symbol: "AMZN", name: "Amazon", price: 488.6 },
  { symbol: "FB", name: "Facebook", price: 189.4 },
  { symbol: "TSLA", name: "Tesla", price: 396.9 },
  { symbol: "NFLX", name: "Netflix", price: 272.1 },
  { symbol: "NVDA", name: "NVIDIA", price: 213.5 },
  { symbol: "PYPL", name: "PayPal", price: 142.2 },
  { symbol: "V", name: "Visa", price: 268.7 },
  { symbol: "DIS", name: "Walt Disney", price: 210.8 },
  { symbol: "JPM", name: "JPMorgan Chase", price: 94.6 },
  { symbol: "WMT", name: "Walmart", price: 108.2 },
  { symbol: "PG", name: "Procter & Gamble", price: 154.9 },
  { symbol: "CRM", name: "Salesforce", price: 328.4 },
  { symbol: "KO", name: "Coca-Cola", price: 84.5 },
  { symbol: "MCD", name: "McDonald's", price: 214.6 },
  { symbol: "HD", name: "Home Depot", price: 450.2 },
  { symbol: "INTC", name: "Intel", price: 75.8 },
  { symbol: "CMCSA", name: "Comcast", price: 59.3 },
  { symbol: "PEP", name: "PepsiCo", price: 134.7 },
  { symbol: "ADBE", name: "Adobe", price: 285.1 },
  { symbol: "XOM", name: "Exxon Mobil", price: 82.6 },
  { symbol: "COST", name: "Costco Wholesale", price: 372.9 },
  { symbol: "IBM", name: "IBM", price: 187.3 },
  { symbol: "NKE", name: "NIKE", price: 117.4 },
  { symbol: "ABT", name: "Abbott Laboratories", price: 292.8 },
  { symbol: "BAC", name: "Bank of America", price: 63.2 },
  { symbol: "BA", name: "Boeing", price: 321.5 },
  { symbol: "CAT", name: "Caterpillar", price: 209.6 },
];

export default defaultStocks;
