const defaultStocks = [
  { symbol: "AAPL", name: "Apple Inc.", price: 150.25, quantity: 0 },
  { symbol: "GOOGL", name: "Alphabet Inc.", price: 2500.75, quantity: 0 },
  {
    symbol: "MSFT",
    name: "Microsoft Corporation",
    price: 300.5,
    quantity: 0,
  },
  { symbol: "AMZN", name: "Amazon.com Inc.", price: 3400.0, quantity: 0 },
  { symbol: "FB", name: "Meta Platforms Inc.", price: 300.75, quantity: 0 },
  { symbol: "TSLA", name: "Tesla, Inc.", price: 750.2, quantity: 0 },
  { symbol: "NFLX", name: "Netflix, Inc.", price: 500.8, quantity: 0 },
  { symbol: "NVDA", name: "NVIDIA Corporation", price: 700.3, quantity: 0 },
  {
    symbol: "PYPL",
    name: "PayPal Holdings, Inc.",
    price: 220.45,
    quantity: 0,
  },
  { symbol: "V", name: "Visa Inc.", price: 220.75, quantity: 0 },
  {
    symbol: "DIS",
    name: "The Walt Disney Company",
    price: 180.9,
    quantity: 0,
  },
  { symbol: "JPM", name: "JPMorgan Chase & Co.", price: 160.6, quantity: 0 },
  { symbol: "WMT", name: "Walmart Inc.", price: 140.25, quantity: 0 },
  {
    symbol: "PG",
    name: "Procter & Gamble Company",
    price: 120.75,
    quantity: 0,
  },
  { symbol: "CRM", name: "Salesforce.com Inc.", price: 250.5, quantity: 0 },
  { symbol: "KO", name: "The Coca-Cola Company", price: 60.3, quantity: 0 },
  {
    symbol: "MCD",
    name: "McDonald's Corporation",
    price: 220.8,
    quantity: 0,
  },
  { symbol: "HD", name: "The Home Depot, Inc.", price: 310.4, quantity: 0 },
  { symbol: "INTC", name: "Intel Corporation", price: 60.5, quantity: 0 },
  { symbol: "CMCSA", name: "Comcast Corporation", price: 50.7, quantity: 0 },
  { symbol: "PEP", name: "PepsiCo, Inc.", price: 150.2, quantity: 0 },
  { symbol: "ADBE", name: "Adobe Inc.", price: 520.9, quantity: 0 },
  {
    symbol: "XOM",
    name: "Exxon Mobil Corporation",
    price: 60.4,
    quantity: 0,
  },
  {
    symbol: "COST",
    name: "Costco Wholesale Corporation",
    price: 450.3,
    quantity: 0,
  },
  {
    symbol: "IBM",
    name: "International Business Machines Corporation",
    price: 130.6,
    quantity: 0,
  },
  { symbol: "NKE", name: "NIKE, Inc.", price: 170.2, quantity: 0 },
  { symbol: "ABT", name: "Abbott Laboratories", price: 130.8, quantity: 0 },
  {
    symbol: "BAC",
    name: "Bank of America Corporation",
    price: 40.25,
    quantity: 0,
  },
  { symbol: "BA", name: "The Boeing Company", price: 210.75, quantity: 0 },
  { symbol: "CAT", name: "Caterpillar Inc.", price: 180.4, quantity: 0 },
];

export default defaultStocks;
